name: "Exemplo de CD"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Pull Docker image
        run: docker pull amandaribeiro/nexus-api:latest

      - name: Stop Docker container
        run: docker stop nexus-api || true

      - name: Remove Docker container
        run: docker rm nexus-api || true

      - name: Run Docker container
        run: |
          docker run --name nexus-api -d -p 8080:8080 \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
            --restart unless-stopped \
            amandaribeiro/nexus-api:latest

      - name: Clean up unused Docker images
        run: docker image prune -f
