name: Exemplo de CI # Nome do workflow

on:
  push: # Evento que dispara o workflow
    branches: [main] # Branch que dispara o workflow

jobs:
  build: # Primeiro trabalho: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout code # Passo para clonar o repositório
        uses: actions/checkout@v4

      - name: Set up JDK 17 # Configuração do JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven # Build do projeto com Maven
        run: mvn -B package -DskipTests
